### ISSUE TITLE
22.5.0: sphinx warnings `reference target not found`

### ISSUE THREAD

**Issue by kloczek** [twisted/pydoctor#555] opened 2022-05-01 19:24 UTC
On building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.
Here is the output with warnings:
```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v4.5.0
Initializing Spelling Checker 7.3.2
making output directory... done
loading intersphinx inventory from https://twistedmatrix.com/documents/current/api/objects.inv...
loading intersphinx inventory from https://bw2.github.io/ConfigArgParse/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 22 added, 0 changed, 0 removed
reading sources... [100%] transition
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... pydoctor.1 { quickstart codedoc docformat/index docformat/epytext docformat/epytext/epytext_demo docformat/restructuredtext docformat/restructuredtext/restructuredtext_demo docformat/google-numpy docformat/google/google_demo docformat/numpy/numpy_demo sphinx-integration customize help faq transition contrib readme api/index } /home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/docs/source/docformat/google-numpy.rst:22: WARNING: py:mod reference target not found: pydoctor.napoleon
/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/docs/source/sphinx-integration.rst:75: WARNING: py:mod reference target not found: pydoctor.sphinx_ext.build_apidocs
/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/docs/source/customize.rst:103: WARNING: py:mod reference target not found: pydoctor.qnmatch
/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/docs/source/customize.rst:111: WARNING: py:class reference target not found: pydoctor.zopeinterface.ZopeInterfaceSystem
/home/tkloczko/rpmbuild/BUILD/pydoctor-22.5.0/docs/source/customize.rst:125: WARNING: py:class reference target not found: pydoctor.templatewriter.TemplateWriter
done
build succeeded, 5 warnings.
```

**Comment by tristanlatr** [comment] 2022-05-01 19:28
Hello @kloczek,

You're missing our inthersphinx URL, please add `--inthersphinx=https://pydoctor.readthedocs.io/en/latest/api/objects.inv`

**Comment by tristanlatr** [comment] 2022-05-01 19:39
Hi @kloczek, sorry I did not understand the issue at first glance. It seems that the pydoctor intersphinx is not added your sphinx app. 

We're using `tox` to test pydoctor, maybe you would have more luck by using it as well? Because right now, it passes inside `tox` env, with flag `-W -n`.

**Comment by kloczek** [comment] 2022-05-02 15:08
Using tox IMO is wrong because it assumes that documentation will be generated against installed module and it requires install module. Only handful of python modules still is doing that and NONE of the non-python projects.

Nevertheless probably you are using tox because with current source tree it is not possible to use directly `sphinx-build`.
To fix that I'm using patch
```patch
--- a/docs/source/conf.py~      2022-03-31 14:37:49.000000000 +0000
+++ b/docs/source/conf.py       2022-05-01 18:55:06.479309978 +0000
@@ -10,9 +10,9 @@
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
 #
-# import os
-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import os
+import sys
+sys.path.insert(0, os.path.abspath('../..'))

 import os
 import subprocess
```
That patch fixes exactly what is mentioned in the comment above modified lines and it allows skip assembly tox venv. In other words: with that patch it is quarantine that documentation will be generated out of source tree (like in any other project outside python domain) and it allows generate documentation faster (KISS principle).

**Comment by tristanlatr** [comment] 2022-05-02 15:51
Hi @kloczek,

I think what your talking about it unrelated to the issue your facing. Pydoctor works by static analysis, `sys.path` tweaks should not be necessary. 

I suspect, because of the `-b man` argument, the local inventory are not generated. 
The core of the issue is here: https://github.com/twisted/pydoctor/blob/018971f1deda1af77bf6b07bc445c41c5c95cef2/pydoctor/sphinx_ext/build_apidocs.py#L77

**Comment by kloczek** [comment] 2022-05-02 15:55
> I think what your talking about it unrelated to the issue your facing. Pydoctor works by static analysis, `sys.path` tweaks should not be necessary.

That patch it is not `pydoctor` tweak. It is tweak of the sphinx copy.py file to allow build `pydoctor` documentation without have `pydoctor` installed 😋 
Just please try that command which is on top of this ticket 😄

**Comment by tristanlatr** [comment] 2022-05-02 16:19
> That patch it is not pydoctor tweak. It is tweak of the sphinx copy.py file to allow build pydoctor documentation without have pydoctor installed 😋

OK I get it now, but I'm usure if it's the best way to fix the issue. Would it be possible to use `PYTHONPATH` env variable to fix importing `pydoctor` without touching the `conf.py`?

Also, it seems that there is another potential issue: right now, the local `objects.inv` (which is used to resolve the links to `pydoctor.*`) is generated only if the builder is `html`, so it's normal to me that some links can't resolve when building with `-b man`

See https://github.com/twisted/pydoctor/blob/018971f1deda1af77bf6b07bc445c41c5c95cef2/pydoctor/sphinx_ext/build_apidocs.py#L77

> Just please try that command which is on top of this ticket 😄

I'll try it out when I have a moment, yes.

**Comment by kloczek** [comment] 2022-05-02 16:31
FYI that teak is even mentioned in template/example sphinx copy.py file https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

**Comment by tristanlatr** [comment] 2022-05-05 17:18
@kloczek, I've tried the following command locally 

`sphinx-build -n -T -b man docs/source build/man`

And of course, if `pydoctor` is not accessible in `PYTHONPATH`, it fails with an `ImportError`. But I don't understand how this has anything to do with the sphinx warning "reference target not found". 

When pydoctor (and all docs requirements) are accessible in the path (either installed or the `sys.path` is teaked), the command fails with the 2 warnings listed up-there. 

Again, the reason for those warnings is that the sphinx inventory of `pydoctor` is not loaded in the sphinx app, because the builder name is 'man' and not 'html'. Currently, the sphinx integration only works for HTML builds, simply because `pydoctor` only outputs HTML for now. 

Hope this helps,

**Comment by tristanlatr** [comment] 2022-05-05 19:18
@kloczek, all I’m saying it that tweaking the `sys.path` will not make these warnings disappear.

Now, if you like to submit a pull request in which you tweak the `sys.path` in `conf.py` such that the docs can be generated without `pydoctor` being installed, please go ahead and I’ll accept it.

**Comment by kloczek** [comment] 2022-05-06 20:22
> @kloczek, all I’m saying it that tweaking the `sys.path` will not make these warnings disappear.

And that what I said as well 😄 
That patch fixes building documentation without installing it.
In other words this ticket is about two independent issues.

**Comment by kloczek** [comment] 2022-05-11 06:17
Issu eis that seruptools<>sphins integration is already sheduled as deprecated.
With that I've started switching in my build procedures to use straight `sphinx-build` command so in such case that small patch is necessary 🤔 
IMO documentation shoul be always build out of source tree (like it is in any project outside pytthon modules domain).

Warnings it is separated subject.

**Comment by tristanlatr** [comment] 2022-05-11 13:25
Whether the documentation have specific requirements is not a problem in my opinion.

Now, I'll close this issue since there is no way to get the man page build work for now and it looks like these warnings are not a real problem. 

Please next time do not talk about two independent issue in the same ticket, this will avoid confusion.

**Closed by tristanlatr** 2022-05-11 13:25 UTC

**Comment by kloczek** [comment] 2022-05-11 14:45
FYI: those refs as links are rendered only in html outpout.

**Comment by kloczek** [comment] 2024-05-27 14:25
Gentle ping .. any update? 🤔 
Just tested 24.3.3 and I still see nitpick watings
```console
+ /usr/bin/sphinx-build -n -T -b man docs/source build/sphinx/man
Running Sphinx v7.3.7
Initializing Spelling Checker 8.0.0
loading intersphinx inventory from https://tristanlatr.github.io/apidocs/twisted/objects.inv...
loading intersphinx inventory from https://bw2.github.io/ConfigArgParse/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 22 added, 0 changed, 0 removed
reading sources... [100%] transition
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-pydoctor.3 { quickstart codedoc docformat/index docformat/epytext docformat/epytext_demo/index docformat/restructuredtext docformat/restructuredtext_demo/index docformat/google-numpy docformat/google_demo/index docformat/numpy_demo/index sphinx-integration customize help faq transition contrib readme api/index } /home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/docformat/google-numpy.rst:22: WARNING: py:mod reference target not found: pydoctor.napoleon
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/sphinx-integration.rst:75: WARNING: py:mod reference target not found: pydoctor.sphinx_ext.build_apidocs
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:103: WARNING: py:mod reference target not found: pydoctor.qnmatch
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:111: WARNING: py:class reference target not found: pydoctor.model.System
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:127: WARNING: py:class reference target not found: pydoctor.extensions.ExtRegistrar
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:133: WARNING: py:class reference target not found: pydoctor.model.Documentable
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:136: WARNING: py:mod reference target not found: pydoctor.extensions.zopeinterface
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:136: WARNING: py:mod reference target not found: pydoctor.extensions.deprecate
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:212: WARNING: py:class reference target not found: pydoctor.model.System
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:212: WARNING: py:meth reference target not found: pydoctor.model.System.__init__
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:212: WARNING: py:class reference target not found: pydoctor.sphinx.SphinxInventory
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:218: WARNING: py:mod reference target not found: pydoctor.extensions
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:224: WARNING: py:class reference target not found: pydoctor.templatewriter.TemplateWriter
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:224: WARNING: py:class reference target not found: pydoctor.templatewriter.IWriter
/home/tkloczko/rpmbuild/BUILD/pydoctor-24.3.3/docs/source/customize.rst:229: WARNING: py:class reference target not found: pydoctor.templatewriter.IWriter
done
build succeeded, 15 warnings.
```

**Comment by kloczek** [comment] 2024-05-27 17:22
Man page is perfectly fine and nothing is missing for that.
Nitpick warnings are affecting html, qch and pdf output.
In rendered document exact keywords are only highlighted without links.

Please use `-n` option to see the same warnings.

**Comment by kloczek** [comment] 2024-06-01 07:21
> edit: But with the patch of sys.path it might do the trick with the html build only, not the man pages build.

FYI I'm using such patch
```patch
--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -10,9 +10,9 @@
 # add these directories to sys.path here. If the directory is relative to the
 # documentation root, use os.path.abspath to make it absolute, like shown here.
 #
-# import os
-# import sys
-# sys.path.insert(0, os.path.abspath('.'))
+import os
+import sys
+sys.path.insert(0, os.path.abspath("../.."))

 import os
 import subprocess
```
Do you want above as PR? 🤔
