### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [twisted/pydoctor#148] opened 2018-10-01 21:15 UTC
I can not find any documentation for pydoctor. I don't see how to use it. Any examples?

**Comment by shaypal5** [comment] 2019-12-14 16:16
This is still true a year later, and especially painful since this is a package meant to automatically generate documentation for packages. :\

**Comment by tristanlatr** [comment] 2020-10-22 15:31
Hi,

I'm proposing myself to be assigned to this ticket. 
It's indeed a bit painful not to have clearer docs than text files... 

What I can do:
- Create actual documentation with sphinx that will contain:
    - Usage exemples:
        - How to autogenerate docs in GitHub actions and push them to gh-pages
    - List of all supported epytext and ReST fields / directives
    - The result of `pydoctor -h`. Dynamically of course
    - List of unsupported ReST fields
- Setup a GitHub action to publish this documentation to readthedocs if that's ok with you

- Better help text for:
    - `--docformat`: Cite the tow supported format: `epytext` and `restructuredtext`
    - `--html-viewsource-base`: Add exemple: ` https://github.com/user/repo/blob/master/`

What will be an issue for me:
- Use case with options `--input-pickle`, `--output-pickle`, `--extra-system`, `--system-class`
- Usage of config file, I can't guess what's the config format...
- Probably other things also

**Comment by tristanlatr** [comment] 2020-10-22 15:31
@mthuurne

**Comment by tristanlatr** [comment] 2020-10-22 17:29
After looking at the configfile parsing code here: https://github.com/twisted/pydoctor/blob/58847e4563398d991e7fc1ce8c388d6e210408af/pydoctor/driver.py#L181

Understood the format is:
```
key:value
```

Exemple:
```
docformat:plaintext
```

I suspect the config file do not work for the `store_true` actions. And I can't get it work with `add-module` or `html-viewsource-base` (invalid option).

Anyway this is just for record so I don't forget about it writing the docs

**Comment by mthuurne** [comment] 2020-10-22 19:03
First, a big thank you for wanting to work on this!

>       * List of all supported epytext and ReST fields / directives

Epytext should be almost fully supported, since I imported the actual epydoc code into pydoctor. What was removed is the `X{foo}` syntax for index terms.

For ReST, as we found out in #225, some directives are supported even though pydoctor doesn't handle them, because doctools takes care of them. So it will take some digging or experimenting to figure out exactly which directives are supported.

>       * The result of `pydoctor -h`. Dynamically of course

Currently the options parsing is done with `optparse` (in `driver.py`). Since `optparse` isn't developed anymore, it would make sense to migrate to for example `argparse` or [Click](https://click.palletsprojects.com/). Whether you're planning to gather the options using screen scraping or introspection, that would be something to keep in mind.

>       * List of unsupported ReST fields

I guess that once you have the full list of supported fields, you also know the unsupported ones.

>     * Setup a GitHub action to publish this documentation to readthedocs if that's ok with you

Yes, please.

>     * Better help text for:
>       
>       * `--docformat`: Cite the tow supported format: `epytext` and `restructuredtext`

We also support a third format: `plaintext`. It mostly serves as a fallback to display syntactically incorrect docstrings, but in theory a user can select it explicitly.

Ideally the list would be built by enumerating submodules of `pydoctor.epydoc.markup`, but if that's too much work, hardcoding it would be fine as well. I hope there will be other formats added in the future, but I don't expect that to happen very often.

>       * `--html-viewsource-base`: Add exemple: ` https://github.com/user/repo/blob/master/`

For Twisted, the link used is `https://github.com/twisted/twisted/tree/twisted-<version>/src`. Pointing to a specific tag rather than a branch is important, since line numbers aren't going to match otherwise when commits are added to the branch after the documentation has been published.

> What will be an issue for me:
> 
>     * Use case with options `--input-pickle`, `--output-pickle`, `--extra-system`, `--system-class`

The system pickle feature was removed a while ago. Are you looking at an older pydoctor or are there still remnants of it in the current version?

`--system-class` still works and is in fact used by Twisted. However, there should be a warning attached that pydoctor currently doesn't have a stable API, so a system class (which is basically a type of plugin) is prone to breaking.

>     * Usage of config file, I can't guess what's the config format...

I have never actually used a config file with pydoctor. Looking at the code, it seems to work like this:
* line-based format
* lines starting with `#` are comments
* non-comment lines contain key-value pairs separated by `:`
* `os.path.expanduser` is applied to the value
* if the option takes a list, `,` is used as the separator for the value

I'm wondering though if it wouldn't be easier to just use INI or TOML as the format. That would allow using a standard parser and we could refer to existing format documentation.

>     * Probably other things also

Please let me know when you run into these.

**Comment by tristanlatr** [comment] 2020-10-22 20:28
> First, a big thank you for wanting to work on this!

You are very welcome, I hope this work can help more people transition from `pdoc3` to `pydoctor`.

> Are you looking at an older pydoctor or are there still remnants of it in the current version?

Yes I was actually looking at the manage here: http://manpages.ubuntu.com/manpages/trusty/man1/pydoctor.1.html

> Ideally the list would be built by enumerating submodules of pydoctor.epydoc.markup

I'll se what I can do about that, should not be too complicated

> Pointing to a specific tag rather than a branch is important

Will make that clear in the docs.

> Whether you're planning to gather the options using screen scraping or introspection, that would be something to keep in mind.

I will just include the output of `pydoctor -h` into one of the docs file, nothing fancy 

> I'm wondering though if it wouldn't be easier to just use INI

I agree this is nonsense to me

Other things:

- I intent to move some of the readme documentation to other place, like change log and Sphinx Integration but I'll keep the usage exemple and list of supported format.

**Comment by tristanlatr** [comment] 2020-10-22 21:32
Also this Wikipedia page should be edited to add pydoctor: https://en.wikipedia.org/wiki/Comparison_of_documentation_generators

**Comment by mthuurne** [comment] 2020-10-22 23:37
> You are very welcome, I hope this work can help more people transition from `pdoc3` to `pydoctor`.

That's how I ended up here as well. I was looking for more or less the Python equivalent of JavaDoc and Sphinx + autodoc didn't provide that, the original `pdoc` wasn't maintained anymore and I wanted support for type annotations, while `pdoc3` has swastikas on its web site.

> I intent to move some of the readme documentation to other place, like change log and Sphinx Integration but I'll keep the usage exemple and list of supported format.

I would like the change log to remain in the README, since that makes it easy to find on PyPI and GitHub. Maybe we'll have to reconsider if it becomes too long at some point, but for now the size is manageable.

I agree with moving the Sphinx Integration docs; the only reason they're in the README is because there wasn't any other place to put them yet.

> Also this Wikipedia page should be edited to add pydoctor: https://en.wikipedia.org/wiki/Comparison_of_documentation_generators

It would be good to have pydoctor listed, but I'd have to submit an item via the discussion page then, since editing directly would violate their conflict-of-interest guidelines. In any case it would be best to submit after the next major release, when "parameter types extracted" will be "yes".

**Comment by mthuurne** [comment] 2020-10-23 04:24
> > Ideally the list would be built by enumerating submodules of pydoctor.epydoc.markup
> 
> I'll se what I can do about that, should not be too complicated

It's not as easy as it may seem, because Python packages can run directly from ZIP files, so listing directory contents isn't going to work in all cases.

The best way I found so far is to do it via [importlib.resources.contents()](https://docs.python.org/3/library/importlib.html#importlib.resources.contents), but that's a Python 3.7 feature and pydoctor currently only requires Python 3.6, so we'd either have to bump the version requirement or rely on the `importlib_resources` backport.

Here is [an example](https://github.com/boxingbeetle/softfab/blob/35b65380/src/softfab/utils.py#L510) from one of my projects. For the help text, we wouldn't have to actually import the modules, only list the module names.

**Comment by tristanlatr** [comment] 2020-10-23 15:04
> while pdoc3 has swastikas on its web site.

So f*cked up, can't believe company like google and microsoft actually use this software. I sent them an email to ask them to consider moving away from pdco3, and I encourage everyone to do the same. There is 0 social acceptation for this, big corp should be the first to cancel it. 

I think I'll do a special documentation page to transition from pdoc3 to pydoctor. I hit a couple bummer while doing so with my project (like convert markdown docstrings to kindda reST and dealing with `@property` #233)

> rely on the importlib_resources backport

Sounds good to me, I don't have a strong opinion on this

> I would like the change log to remain in the README

Ok !

**Comment by tristanlatr** [comment] 2020-10-23 16:33
Question: What should I do with the todos ?

My point if via it that it should be translated to gh issues so we can remove it

**Comment by tristanlatr** [comment] 2020-10-23 17:00
For now, it looks like this:

![by default 2020-10-23 at 1 00 31 PM](https://user-images.githubusercontent.com/19967168/97032380-bc326e80-152f-11eb-90c7-be592e40824b.png)


Any feedback on the structure ?

**Comment by mthuurne** [comment] 2020-10-24 10:32
Looks good.

"Full help" is the output of `pydoctor --help`? If so, maybe put it as the last subsection of the "Usage" section.

"Epytext support" and "ReStructuredText support" could be subsections of a "Documentation Formats" section.

"Design Notes" could go into a "Development" section, where the release procedure from the README could also be moved to.

Transition help could be a "Transitioning to pydoctor" section with a subsection per tool users might want to transition from. Since epydoc isn't updated anymore, that would be worth dedicating a subsection to as well.

**Comment by mthuurne** [comment] 2020-10-27 09:50
> Question: What should I do with the todos ?
> 
> My point of view it that it should be translated to gh issues so we can remove it

I went through the todos and added an idea to #104. The rest of it either no longer applied or was too vague to make a good ticket.

I'll remove the file.

**Comment by tristanlatr** [comment] 2020-11-03 06:08
Hello All,

So here is the first draft of sphinx documentation for PyDoctor. All feedbacks welcome ! 

https://mfesiem.github.io/pydoctor/index.html

Note that I also published PyDoctor's own API documentation under the `apidocs` folder and used sphinx integration to link to classes in the custom builds section. After merged, `conf.py` needs an edit to point to the final intersphinx URL.

What I did:

- Rename `doc` folder to `docs`
- Write docs - Usage exemples: How to autogenerate docs in GitHub actions and push them to gh-pages, etc...
- Created 2 new github action to generate and publish Sphinx and PyDoctor HTML (tackles #106)
- Edit README.rst (included in the docs)
- Created CONTRIBUTE.rst (included in the docs)
- Edit a few pydoctor docstrings as they were flagged as "bad docstrings"
- Add a warning in `pydoctor/__init__.py`

What I didn't do yet:
- The whole Read The Docs thing, it's working with github pages for now. I understood that Read The Docs builds were triggered with webhooks. That is problematic to include `pydoctor --help` output dynamically. Any thought ?
- Edit `optparse` help texts
- Full list of supported and unsupported ReStructuredText
- Put a link to the docs in the README and maybe add a nice [![Docs](https://img.shields.io/badge/-documentation-blue)]() badge

What I want feedback on:
- Should we say `pydoctor`or PyDoctor ?
- English is not my mother tongue, please feel free to correct any language errors 
- Everything!



Thanks

PS : Got an answer from Microsoft and they are "purging" pdoc3 to use sphinx

**Comment by adiroiban** [comment] 2020-11-03 11:14
Thanks @tristanlatr it looks good. Can we have it as a PR ?

I can set up the webhooks for Read The Docs.

I have created this hack for Twisted to "inject" pydoctor API docs inside Read The Docs - https://github.com/twisted/twisted/pull/1466

If  there is interest outside of twisted, I guess that I can contribute that hack in `pydoctor`. 

Don't worry about your english. During the PR review process we can update that part. 

I think that this is great progress .

Is important to have a start and then we can have future PR to add more info, update existing one...etc

--------

So, @tristanlatr can you please send your changes as a PR and we can look into having it published to Read The Docs ?

Thanks!

**Comment by adiroiban** [comment] 2020-11-03 13:40
@tristanlatr  if you have time, you can join the #twisted-dev IRC channel on FreeNode and we can look into putting your documentation on the pydoctor project on Read The docs.

I have created the RTD project at https://readthedocs.org/projects/pydoctor/
@mthuurne do you have a RTD account?

**Comment by tristanlatr** [comment] 2020-11-03 16:17
> Can we have it as a PR ?

@adiroiban Give me a few days please, there is still a few things that I' de like to put there. Meanwhile, I can integrate general feedbacks

> I can set up the webhooks for Read The Docs.

The thing that would be problematic (I think), it the autogeneration of "Full help". As you can see in the github action workflow file [here](https://github.com/mfesiem/pydoctor/blob/master/.github/workflows/sphinx-docs.yml#L39). Is there a way to reproduce this inside the Shpinx build ?

> you can join the #twisted-dev IRC channel on FreeNode

I'll do that

Also, it would be good to document howto "inject" pydoctor's documentation into Read The Docs in this very documentation. I've review the PR 1466, but I must say I don't quite get it. I guess the core of it it the `docs/_extensions/apidocs.py` file. 

Should we create a proper PyDoctor extension for Sphinx instead of duplicating this very cool work?

**Comment by adiroiban** [comment] 2020-11-03 17:32
@tristanlatr no hurry.

> Should we create a proper PyDoctor extension for Sphinx instead of duplicating this very cool work?

Once we have the basic / simple  Sphinx documentation for pydoctor published  on RTD, I will contribute to the Sphinx extension and document it.

The PR from Twisted is a big hack for Read The docs, as I was not expecting for other people to find it useful. ... but I am happy to move that code to pydoctor.

**Comment by adiroiban** [comment] 2020-11-04 18:44
I think that this is closed by #252 

There is still room for improvements, but I think that we can follow up in separate PRs

**Closed** 2020-11-04 18:44 UTC
