### ISSUE TITLE
Class deprecations should be noted in API

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#65] opened 2015-01-12 22:36 UTC
From https://twistedmatrix.com/trac/ticket/6760:

When a class is deprecated, a note should be added by pydoctor to the class API description.

An example is POP3Client. A deprecation warning is issued in its **init** function. But in the API, it is not obvious that the class should not be used. That comment could be put in explicitly but that would be repeating information.

---

Imported from Launchpad using lp2gh.
- date created: 2013-09-23T22:27:03Z
- owner: mwhudson
- the launchpad url was https://bugs.launchpad.net/bugs/1229447

**Comment by mwhudson** [comment] 2015-01-12 22:43
(by mwhudson)
So the question here is how to tell pydoctor that the class is deprecated.  The rest should be easy <wink>

**Comment by mwhudson** [comment] 2015-01-12 22:43
(by exarkun)
Here's one idea:

    from twisted.python.deprecate import deprecated

    @deprecated(...)
    class SomeDeprecatedThing(object):
        ...

Although since the goal of the deprecation should be for this code to result in a warning being emitted:

    from module import SomeDeprecatedThing

possibly the solution needs to be something more like `deprecatedModuleAttribute`.

I guess the important point is that there are two goals to keep in mind for this one API.  It needs to cause a `DeprecationWarning` to be emitted when the deprecated API is used and it needs to inform pydoctor that it should annotate some generated documentation with deprecation information.

**Comment by mwhudson** [comment] 2015-01-12 22:43
(by mwhudson)
Hm.  So maybe closing the twisted ticket was too hasty?  We could re-purpose it into a "twisted needs an api to mark a class deprecated"... although, is there any reason that deprecatedModuleAttribute isn't sufficient?  I don't think pydoctor does anything special with deprecatedModuleAttribute currently, but it could.

**Comment by adiroiban** [comment] 2020-10-24 15:07
There is now a class deprecation helper in Twisted https://github.com/twisted/twisted/blob/da0bbc698cbb2a48b198987663db0a0c9a19ab8d/src/twisted/python/test/test_deprecate.py#L691 ... so maybe the twisted part is done. :)

**Comment by mthuurne** [comment] 2020-12-11 07:03
I'm closing this one as a duplicate of #319, which contains more detail and is more up-to-date.

**Closed by mthuurne** 2020-12-11 07:03 UTC
