### ISSUE TITLE
unittest helpers(?) for verifying a package has valid docstrings

### ISSUE THREAD

**Issue by mwhudson** [twisted/pydoctor#18] opened 2015-01-12 22:36 UTC
It would be neat if there was some way of having the testsuite verify that the syntax of all docstrings, etc is valid - without generating all the output.

I might have a look at this myself, though hints as how to do this would be much appreciated.

---

Imported from Launchpad using lp2gh.
- date created: 2011-03-26T15:49:20Z
- owner: jelmer
- the launchpad url was https://bugs.launchpad.net/bugs/743185

**Comment by mwhudson** [comment] 2015-01-12 22:38
(by mwhudson)
Yes, this would be nice.  I don't think it would be too hard either, I think you just need to iterate over system.allobjects and call epydoc2stan.doc2html on each object.  The way errors are currently reported is a bit unhelpful for this, but that's probably easy to fix (you could just put reportErrors=reportErrors in doc2html's argument list for a good start I guess!).

**Comment by mthuurne** [comment] 2020-07-08 17:33
I think this is essentially a duplicate of #43.

@jelmer: Feel free to reopen if you disagree.

**Closed by mthuurne** 2020-07-08 17:33 UTC
Labels: Confirmed, Wishlist
